name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: docker --help
          plugin: docker
          skip_install: false
          giturl: https://github.com/doriancodes/asdf-docker
          gitref: main
          asdf_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
